<?php

return [
    [
        'name' => 'Villa sul mare',
        'address' => 'Via del Mare, 00126 Roma',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'piscina', 'posto macchina', 'vista mare'],
        'beds' => 4,
        'bedrooms' => 2,
        'bathrooms' => 1,
        'size' => '100 mq',
        'description' => 'Bellissima villa con piscina privata e vista sul mare',
        'price' => 120.50,
    ],
    [
        'name' => 'Appartamento in centro',
        'address' => 'Piazza del Popolo, 00187 Roma',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'posto macchina'],
        'beds' => 2,
        'bedrooms' => 1,
        'bathrooms' => 1,
        'size' => '50 mq',
        'description' => 'Comodo appartamento in centro città',
        'price' => 60.00,
    ],
    [
        'name' => 'Appartamento di lusso',
        'address' => 'Via Napoleone, 20121 Milano',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'posto macchina'],
        'beds' => 3,
        'bedrooms' => 2,
        'bathrooms' => 2,
        'size' => '120 mq',
        'description' => 'Appartamento di lusso nel cuore di Milano',
        'price' => 150.00,
    ],
    [
        'name' => 'Casa vacanze in montagna',
        'address' => 'Via Stazione, 32043 Cortina d\'Ampezzo',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'posto macchina'],
        'beds' => 6,
        'bedrooms' => 3,
        'bathrooms' => 2,
        'size' => '150 mq',
        'description' => 'Casa vacanze in montagna con vista panoramica',
        'price' => 70.00,
    ],
    [
        'name' => 'Appartamento di lusso',
        'address' => 'Via Monte Napoleone, 20121 Milano',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'posto macchina'],
        'beds' => 3,
        'bedrooms' => 2,
        'bathrooms' => 2,
        'size' => '120 mq',
        'description' => 'Appartamento di lusso nel cuore di Milano',
        'price' => 200.00,
    ],
    [
        'name' => 'Casa vacanze in montagna',
        'address' => 'Via Faloria, 32043 Cortina d\'Ampezzo',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'posto macchina'],
        'beds' => 6,
        'bedrooms' => 3,
        'bathrooms' => 2,
        'size' => '150 mq',
        'description' => 'Casa vacanze in montagna con vista panoramica',
        'price' => 90.00,
    ],
    [
        'name' => 'Appartamento con terrazza',
        'address' => 'Piazza Navona, 00186 Roma',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'posto macchina'],
        'beds' => 4,
        'bedrooms' => 2,
        'bathrooms' => 1,
        'size' => '80 mq',
        'description' => 'Appartamento di design con terrazza panoramica',
        'price' => 120.00,
    ],
    [
        'name' => 'Villa toscana con piscina',
        'address' => 'Via del Castello, 53037 San Gimignano SI, Italia',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'piscina', 'posto macchina'],
        'letti' => 10,
        'camere' => 5,
        'bagni' => 5,
        'size' => '400 mq',
        'description' => 'Una bellissima e autentica villa toscana con piscina privata e vista mozzafiato',
        'price' => 300.00,
    ],
    [
        'name' => 'Elegante appartamento nel cuore di Venezia',
        'address' => 'Campo San Polo, 30125 Venezia, Italia',
        'services' => ['Wi-Fi', 'cucina', 'TV'],
        'letti' => 4,
        'camere' => 2,
        'bagni' => 1,
        'size' => '80 mq',
        'description' => 'Un elegante e raffinato appartamento nel cuore di Venezia, a due passi da Piazza San Marco',
        'price' => 250.50,
    ],
    [
        'name' => 'Agriturismo con vista sulle colline del Chianti',
        'address' => 'Via San Giovanni, 50028 Tavarnelle Val di Pesa FI, Italia',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'piscina', 'posto macchina'],
        'letti' => 8,
        'camere' => 4,
        'bagni' => 4,
        'size' => '200 mq',
        'description' => 'Un bellissimo agriturismo immerso nelle colline del Chianti, con piscina panoramica',
        'price' => 140.70,
    ],
    [
        'name' => 'Appartamento di lusso con vista sulle Cinque Terre',
        'address' => 'Via Mazzini, 19018 Vernazza SP, Italia',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'vista mare'],
        'letti' => 4,
        'camere' => 2,
        'bagni' => 2,
        'size' => '120 mq',
        'description' => 'Un appartamento di lusso situato nel cuore delle Cinque Terre, con una vista mozzafiato sul mare',
        'price' => 400.00,
    ],
    [
        'name' => 'Villa con piscina in Umbria',
        'address' => 'Via Del Porto, 06069 Tuoro sul Trasimeno PG, Italia',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'piscina', 'posto macchina'],
        'letti' => 6,
        'camere' => 3,
        'bagni' => 3,
        'size' => '150 mq',
        'description' => 'Una bellissima villa immersa nella campagna umbra, con piscina privata e vista panoramica',
        'price' => 300.00,
    ],
    [
        'name' => 'Appartamento con terrazza nel centro di Firenze',
        'address' => 'Piazza della Signoria, 50122 Firenze FI, Italia',
        'services' => ['Wi-Fi', 'cucina', 'TV'],
        'letti' => 2,
        'camere' => 1,
        'bagni' => 1,
        'size' => '50 mq',
        'description' => 'Un accogliente appartamento nel cuore di Firenze, con una splendida terrazza panoramica',
        'price' => 180.00,
    ],
    [
        'name' => 'Villa sul Lago di Como',
        'address' => 'Via Regina, 22010 Cernobio, Italia',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'piscina', 'posto macchina'],
        'letti' => 8,
        'camere' => 4,
        'bagni' => 3,
        'size' => '200 mq',
        'description' => 'Una bellissima villa sul Lago di Como, con piscina privata e vista panoramica',
        'price' => 300.00,
    ],
    [
        'name' => 'Appartamento con terrazza a Sorrento',
        'address' => 'Corso Italia, 80067 Sorrento NA, Italia',
        'services' => ['Wi-Fi', 'cucina', 'TV'],
        'letti' => 4,
        'camere' => 2,
        'bagni' => 2,
        'size' => '100 mq',
        'description' => 'Un grazioso appartamento con terrazza nel centro di Sorrento',
        'price' => 80.00,
    ],
    [
        'name' => 'Casa vacanza a San Vito lo Capo',
        'address' => 'Via del Mandarino, 91010 San Vito Lo Capo TP, Italia',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'posto macchina', 'vista mare'],
        'letti' => 6,
        'camere' => 3,
        'bagni' => 2,
        'size' => '120 mq',
        'description' => 'Una confortevole casa vacanza con vista sul mare di San Vito lo Capo',
        'price' => 300.00,
    ],
    [
        'name' => 'Casa di campagna',
        'address' => 'Via dei Melograni, 50142 Firenze',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'giardino', 'posto macchina'],
        'beds' => 6,
        'bedrooms' => 3,
        'bathrooms' => 2,
        'size' => '120 mq',
        'description' => 'Affascinante casa di campagna con vista panoramica sulla campagna toscana',
        'price' => 100.00,
    ],
    [
        'name' => 'Attico di lusso',
        'address' => 'Viale della Vittoria, 00122 Roma',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'ascensore'],
        'beds' => 2,
        'bedrooms' => 1,
        'bathrooms' => 1,
        'size' => '80 mq',
        'description' => 'Esclusivo attico con terrazza panoramica nel cuore di Roma',
        'price' => 800.00,
    ],
    [
        'name' => 'Casa in collina',
        'address' => 'Viale dei Pini, 50142 Firenze',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'posto macchina'],
        'beds' => 3,
        'bedrooms' => 2,
        'bathrooms' => 1,
        'size' => '90 mq',
        'description' => 'Affascinante casa con vista sulla collina toscana',
        'price' => 300.00,
    ],
    [
        'name' => 'Appartamento al mare',
        'address' => 'Viale Trento, 47921 Rimini',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'aria condizionata', 'posto macchina', 'vista mare'],
        'beds' => 4,
        'bedrooms' => 2,
        'bathrooms' => 2,
        'size' => '70 mq',
        'description' => 'Accogliente appartamento con vista sul mare adriatico',
        'price' => 90.00,
    ],
    [
        'name' => 'Villa in campagna',
        'address' => 'Via delle Rose, 50025 Montespertoli',
        'services' => ['Wi-Fi', 'cucina', 'TV', 'piscina', 'posto macchina'],
        'beds' => 10,
        'bedrooms' => 5,
        'bathrooms' => 4,
        'size' => '300 mq',
        'description' => 'Splendida villa con piscina privata e vista sulla campagna toscana',
        'price' => 70.00,
    ],
    [
        'name' => 'Monolocale nel centro storico',
        'address' => 'Via dei Benci, 50122 Firenze',
        'services' => ['Wi-Fi', 'cucina', 'TV'],
        'beds' => 2,
        'bedrooms' => 0,
        'bathrooms' => 1,
        'size' => '30 mq',
        'description' => 'Accogliente monolocale nel cuore del centro storico',
        'price' => 90.00,
    ],
    [
        'name' => 'Villa degli Ulivi',
        'address' => 'Via degli Ulivi, 95123 Catania CT',
        'services' => ['Wi-Fi', 'Cucina', 'TV', 'Piscina', 'Posto macchina', 'Vista mare'],
        'beds' => 4,
        'rooms' => 2,
        'bathrooms' => 1,
        'size' => '100 m²',
        'description' => 'Splendida villa immersa nel verde degli ulivi, con vista mozzafiato sul mare della Sicilia. Perfetta per una vacanza rilassante e lontana dal caos della città.',
        'price' => 145.50,
    ],
    [
        'name' => 'Casa del Pescatore',
        'address' => 'Via del Mare, 97010 Modica RG',
        'services' => ['Wi-Fi', 'Cucina', 'TV', 'Vista mare'],
        'beds' => 2,
        'rooms' => 1,
        'bathrooms' => 1,
        'size' => '50 m²',
        'description' => 'Deliziosa casetta situata a pochi passi dal mare, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto e dotata di tutti i comfort.',
        'price' => 95.00,
    ],
];
