<?php

return [
    'properties' => [
        [
            'name' => 'Villa sul mare',
            'address' => 'Via del Mare, 00126 Roma',
            'latitude' => '41.79246',
            'longitude' => '12.38622',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => '100 mq',
            'description' => 'Bellissima villa con piscina privata e vista sul mare',
            'price' => 120.50,
        ],
        [
            'name' => 'Appartamento in centro',
            'address' => 'Piazza del Popolo, 00187 Roma',
            'latitude' => '41.91048',
            'longitude' => '12.47623',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => '50 mq',
            'description' => 'Comodo appartamento in centro città',
            'price' => 60.00,
        ],
        [
            'name' => 'Appartamento di lusso',
            'address' => 'Via Napoleone, 20121 Milano',
            'latitude' => '45.46818',
            'longitude' => '9.19532',
            'beds' => 3,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'size' => '120 mq',
            'description' => 'Appartamento di lusso nel cuore di Milano',
            'price' => 150.00,
        ],
        [
            'name' => 'Casa vacanze in montagna',
            'address' => 'Via Stazione, 32043 Cortina d\'Ampezzo',
            'latitude' => '46.53914',
            'longitude' => '12.13643',
            'beds' => 6,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'size' => '150 mq',
            'description' => 'Casa vacanze in montagna con vista panoramica',
            'price' => 70.00,
        ],
        [
            'name' => 'Appartamento di lusso',
            'address' => 'Via Monte Napoleone, 20121 Milano',
            'latitude' => '45.46818',
            'longitude' => '9.19532',
            'beds' => 3,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'size' => '120 mq',
            'description' => 'Appartamento di lusso nel cuore di Milano',
            'price' => 200.00,
        ],
        [
            'name' => 'Casa vacanze in montagna',
            'address' => 'Via Faloria, 32043 Cortina d\'Ampezzo',
            'latitude' => '46.53269',
            'longitude' => '12.14363',
            'beds' => 6,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'size' => '150 mq',
            'description' => 'Casa vacanze in montagna con vista panoramica',
            'price' => 90.00,
        ],
        [
            'name' => 'Appartamento con terrazza',
            'address' => 'Piazza Navona, 00186 Roma',
            'latitude' => '41.89913',
            'longitude' => '12.4732',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => '80 mq',
            'description' => 'Appartamento di design con terrazza panoramica',
            'price' => 120.00,
        ],
        [
            'name' => 'Villa toscana con piscina',
            'address' => 'Via del Castello, 53037 San Gimignano SI, Italia',
            'latitude' => '43.46754',
            'longitude' => '11.04466',
            'beds' => 10,
            'bedrooms' => 5,
            'bathrooms' => 5,
            'size' => '400 mq',
            'description' => 'Una bellissima e autentica villa toscana con piscina privata e vista mozzafiato',
            'price' => 300.00,
        ],
        [
            'name' => 'Elegante appartamento nel cuore di Venezia',
            'address' => 'Campo San Polo, 30125 Venezia, Italia',
            'latitude' => '45.43735',
            'longitude' => '12.3296',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => '80 mq',
            'description' => 'Un elegante e raffinato appartamento nel cuore di Venezia, a due passi da Piazza San Marco',
            'price' => 250.50,
        ],
        [
            'name' => 'Agriturismo con vista sulle colline del Chianti',
            'address' => 'Via San Giovanni, 50028 Tavarnelle Val di Pesa FI, Italia',
            'latitude' => '43.56389',
            'longitude' => '11.17425',
            'beds' => 8,
            'bedrooms' => 4,
            'bathrooms' => 4,
            'size' => '200 mq',
            'description' => 'Un bellissimo agriturismo immerso nelle colline del Chianti, con piscina panoramica',
            'price' => 140.70,
        ],
        [
            'name' => 'Appartamento di lusso con vista sulle Cinque Terre',
            'address' => 'Via Mazzini, 19018 Vernazza SP, Italia',
            'latitude' => '44.13448',
            'longitude' => '9.68334',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'size' => '120 mq',
            'description' => 'Un appartamento di lusso situato nel cuore delle Cinque Terre, con una vista mozzafiato sul mare',
            'price' => 400.00,
        ],
        [
            'name' => 'Villa con piscina in Umbria',
            'address' => 'Via Del Porto, 06069 Tuoro sul Trasimeno PG, Italia',
            'latitude' => '43.20603',
            'longitude' => '12.07734',
            'beds' => 6,
            'bedrooms' => 3,
            'bathrooms' => 3,
            'size' => '150 mq',
            'description' => 'Una bellissima villa immersa nella campagna umbra, con piscina privata e vista panoramica',
            'price' => 300.00,
        ],
        [
            'name' => 'Appartamento con terrazza nel centro di Firenze',
            'address' => 'Piazza della Signoria, 50122 Firenze FI, Italia',
            'latitude' => '43.76954',
            'longitude' => '11.25598',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => '50 mq',
            'description' => 'Un accogliente appartamento nel cuore di Firenze, con una splendida terrazza panoramica',
            'price' => 180.00,
        ],
        [
            'name' => 'Villa sul Lago di Como',
            'address' => 'Via Regina, 22010 Cernobio, Italia',
            'latitude' => '45.8523',
            'longitude' => '9.08894',
            'beds' => 8,
            'bedrooms' => 4,
            'bathrooms' => 3,
            'size' => '200 mq',
            'description' => 'Una bellissima villa sul Lago di Como, con piscina privata e vista panoramica',
            'price' => 300.00,
        ],
        [
            'name' => 'Appartamento con terrazza a Sorrento',
            'address' => 'Corso Italia, 80067 Sorrento NA, Italia',
            'latitude' => '40.62676',
            'longitude' => '14.38085',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'size' => '100 mq',
            'description' => 'Un grazioso appartamento con terrazza nel centro di Sorrento',
            'price' => 80.00,
        ],
        [
            'name' => 'Casa vacanza a San Vito lo Capo',
            'address' => 'Via del Mandarino, 91010 San Vito Lo Capo TP, Italia',
            'latitude' => '38.13129',
            'longitude' => '12.73482',
            'beds' => 6,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'size' => '120 mq',
            'description' => 'Una confortevole casa vacanza con vista sul mare di San Vito lo Capo',
            'price' => 300.00,
        ],
        [
            'name' => 'Casa di campagna',
            'address' => 'Via dei Melograni, 50142 Firenze',
            'latitude' => '43.77741',
            'longitude' => '11.22011',
            'beds' => 6,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'size' => '120 mq',
            'description' => 'Affascinante casa di campagna con vista panoramica sulla campagna toscana',
            'price' => 100.00,
        ],
        [
            'name' => 'Attico di lusso',
            'address' => 'Viale della Vittoria, 00122 Roma',
            'latitude' => '41.72929,',
            'longitude' => '12.28798',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => '80 mq',
            'description' => 'Esclusivo attico con terrazza panoramica nel cuore di Roma',
            'price' => 800.00,
        ],
        [
            'name' => 'Casa in collina',
            'address' => 'Viale dei Pini, 50142 Firenze',
            'latitude' => '43.77924',
            'longitude' => '11.21495',
            'beds' => 3,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => '90 mq',
            'description' => 'Affascinante casa con vista sulla collina toscana',
            'price' => 300.00,
        ],
        [
            'name' => 'Appartamento al mare',
            'address' => 'Viale Trento, 47921 Rimini',
            'latitude' => '44.06591',
            'longitude' => '12.5792',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'size' => '70 mq',
            'description' => 'Accogliente appartamento con vista sul mare adriatico',
            'price' => 90.00,
        ],
        [
            'name' => 'Villa in campagna',
            'address' => 'Via delle Rose, 50025 Montespertoli',
            'latitude' => '43.69627,',
            'longitude' => '11.01391',
            'beds' => 10,
            'bedrooms' => 5,
            'bathrooms' => 4,
            'size' => '300 mq',
            'description' => 'Splendida villa con piscina privata e vista sulla campagna toscana',
            'price' => 70.00,
        ],
        [
            'name' => 'Monolocale nel centro storico',
            'address' => 'Via dei Benci, 50122 Firenze',
            'latitude' => '43.76767',
            'longitude' => '11.2594',
            'beds' => 2,
            'bedrooms' => 0,
            'bathrooms' => 1,
            'size' => '30 mq',
            'description' => 'Accogliente monolocale nel cuore del centro storico',
            'price' => 90.00,
        ],
        [
            'name' => 'Villa degli Ulivi',
            'address' => 'Via degli Ulivi, 95123 Catania CT',
            'latitude' => '37.52557',
            'longitude' => '15.05628',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => '100 m²',
            'description' => 'Splendida villa immersa nel verde degli ulivi, con vista mozzafiato sul mare della Sicilia. Perfetta per una vacanza rilassante e lontana dal caos della città.',
            'price' => 145.50,
        ],
        [
            'name' => 'Casa del Pescatore',
            'address' => 'Via del Mare, 97010 Modica RG',
            'latitude' => '36.7128',
            'longitude' => '14.77913',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => '50 m²',
            'description' => 'Deliziosa casetta situata a pochi passi dal mare, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto e dotata di tutti i comfort.',
            'price' => 95.00,
        ],
    ],

    'users' => [
        [
            'name' => 'Carmelo',
            'lastname' => 'Palumbo',
            'username' => 'paluc',
            'email' => 'carmelopalumbo@boolbnb.com',
            'password' => '12345678',
            'date_of_birth' => '1997-04-26'
        ],
        [
            'name' => 'Carmelo',
            'lastname' => 'Miuccio',
            'username' => 'themrstraffy',
            'email' => 'carmelomiuccio@boolbnb.com',
            'password' => '12345678',
            'date_of_birth' => '1994-05-27'
        ],
        [
            'name' => 'Eugenio',
            'lastname' => 'Belardinelli',
            'username' => 'eugenio21',
            'email' => 'eugeniobelardinelli@boolbnb.com',
            'password' => '12345678',
            'date_of_birth' => '1992-04-21'
        ],
        [
            'name' => 'Michele',
            'lastname' => 'Zancolò',
            'username' => 'zanco',
            'email' => 'mikyzancolo97@gmail.com',
            'password' => '12345678',
            'date_of_birth' => '1997-05-19'
        ],
        [
            'name' => 'Jessica',
            'lastname' => 'Tartaglia',
            'username' => 'fr_jess',
            'email' => 'jessicatartaglia@gmail.com',
            'password' => '12345678',
            'date_of_birth' => '1985-05-26'
        ]
    ],

    'services' => ['cucina', 'wi-fi', 'posto auto', 'tv', 'piscina', 'aria condizionata', 'vista mare', 'ascensore', 'animali ammessi', 'giardino'],

    'sponsors' => [
        [
            'name' => 'bronze',
            'price' => 2.99,
            'duration' => 86400
        ],
        [
            'name' => 'silver',
            'price' => 5.99,
            'duration' => 259200
        ],
        [
            'name' => 'gold',
            'price' => 9.99,
            'duration' => 518400
        ],
    ]

];
