<?php

return [
    'properties' => [
        [
            'name' => 'Villa sul mare',
            'address' => 'Via del Mare, 00126 Roma',
            'latitude' => '41.79246',
            'longitude' => '12.38622',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => 100,
            'description' => 'Bellissima villa con piscina privata e vista sul mare',
            'price' => 120.50,
        ],
        [
            'name' => 'Appartamento in centro',
            'address' => 'Piazza del Popolo, 00187 Roma',
            'latitude' => '41.91048',
            'longitude' => '12.47623',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Comodo appartamento in centro città',
            'price' => 60.00,
        ],
        [
            'name' => 'Appartamento di lusso',
            'address' => 'Via Napoleone, 20121 Milano',
            'latitude' => '45.46818',
            'longitude' => '9.19532',
            'beds' => 3,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'size' => 120,
            'description' => 'Appartamento di lusso nel cuore di Milano',
            'price' => 150.00,
        ],
        [
            'name' => 'Casa vacanze in montagna',
            'address' => 'Via Stazione, 32043 Cortina d\'Ampezzo',
            'latitude' => '46.53914',
            'longitude' => '12.13643',
            'beds' => 6,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'size' => 150,
            'description' => 'Casa vacanze in montagna con vista panoramica',
            'price' => 70.00,
        ],
        [
            'name' => 'Appartamento di lusso',
            'address' => 'Via Monte Napoleone, 20121 Milano',
            'latitude' => '45.46818',
            'longitude' => '9.19532',
            'beds' => 3,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'size' => 120,
            'description' => 'Appartamento di lusso nel cuore di Milano',
            'price' => 200.00,
        ],
        [
            'name' => 'Casa vacanze in montagna',
            'address' => 'Via Faloria, 32043 Cortina d\'Ampezzo',
            'latitude' => '46.53269',
            'longitude' => '12.14363',
            'beds' => 6,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'size' => 150,
            'description' => 'Casa vacanze in montagna con vista panoramica',
            'price' => 90.00,
        ],
        [
            'name' => 'Appartamento con terrazza',
            'address' => 'Piazza Navona, 00186 Roma',
            'latitude' => '41.89913',
            'longitude' => '12.4732',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => 80,
            'description' => 'Appartamento di design con terrazza panoramica',
            'price' => 120.00,
        ],
        [
            'name' => 'Villa toscana con piscina',
            'address' => 'Via del Castello, 53037 San Gimignano SI, Italia',
            'latitude' => '43.46754',
            'longitude' => '11.04466',
            'beds' => 10,
            'bedrooms' => 5,
            'bathrooms' => 5,
            'size' => 400,
            'description' => 'Una bellissima e autentica villa toscana con piscina privata e vista mozzafiato',
            'price' => 300.00,
        ],
        [
            'name' => 'Elegante appartamento nel cuore di Venezia',
            'address' => 'Campo San Polo, 30125 Venezia, Italia',
            'latitude' => '45.43735',
            'longitude' => '12.3296',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => 80,
            'description' => 'Un elegante e raffinato appartamento nel cuore di Venezia, a due passi da Piazza San Marco',
            'price' => 250.50,
        ],
        [
            'name' => 'Agriturismo con vista sulle colline del Chianti',
            'address' => 'Via San Giovanni, 50028 Tavarnelle Val di Pesa FI, Italia',
            'latitude' => '43.56389',
            'longitude' => '11.17425',
            'beds' => 8,
            'bedrooms' => 4,
            'size' => 200,
            'bathrooms' => 4,
            'description' => 'Un bellissimo agriturismo immerso nelle colline del Chianti, con piscina panoramica',
            'price' => 140.70,
        ],
        [
            'name' => 'Appartamento di lusso con vista sulle Cinque Terre',
            'address' => 'Via Mazzini, 19018 Vernazza SP, Italia',
            'latitude' => '44.13448',
            'longitude' => '9.68334',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'size' => 120,
            'description' => 'Un appartamento di lusso situato nel cuore delle Cinque Terre, con una vista mozzafiato sul mare',
            'price' => 400.00,
        ],
        [
            'name' => 'Villa con piscina in Umbria',
            'address' => 'Via Del Porto, 06069 Tuoro sul Trasimeno PG, Italia',
            'latitude' => '43.20603',
            'longitude' => '12.07734',
            'beds' => 6,
            'bedrooms' => 3,
            'bathrooms' => 3,
            'size' => 150,
            'description' => 'Una bellissima villa immersa nella campagna umbra, con piscina privata e vista panoramica',
            'price' => 300.00,
        ],
        [
            'name' => 'Appartamento con terrazza nel centro di Firenze',
            'address' => 'Piazza della Signoria, 50122 Firenze FI, Italia',
            'latitude' => '43.76954',
            'longitude' => '11.25598',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Un accogliente appartamento nel cuore di Firenze, con una splendida terrazza panoramica',
            'price' => 180.00,
        ],
        [
            'name' => 'Villa sul Lago di Como',
            'address' => 'Via Regina, 22010 Cernobio, Italia',
            'latitude' => '45.8523',
            'longitude' => '9.08894',
            'beds' => 8,
            'bedrooms' => 4,
            'bathrooms' => 3,
            'size' => 200,
            'description' => 'Una bellissima villa sul Lago di Como, con piscina privata e vista panoramica',
            'price' => 300.00,
        ],
        [
            'name' => 'Appartamento con terrazza a Sorrento',
            'address' => 'Corso Italia, 80067 Sorrento NA, Italia',
            'latitude' => '40.62676',
            'longitude' => '14.38085',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'size' => 100,
            'description' => 'Un grazioso appartamento con terrazza nel centro di Sorrento',
            'price' => 80.00,
        ],
        [
            'name' => 'Casa vacanza a San Vito lo Capo',
            'address' => 'Via del Mandarino, 91010 San Vito Lo Capo TP, Italia',
            'latitude' => '38.13129',
            'longitude' => '12.73482',
            'beds' => 6,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'size' => 120,
            'description' => 'Una confortevole casa vacanza con vista sul mare di San Vito lo Capo',
            'price' => 300.00,
        ],
        [
            'name' => 'Casa di campagna',
            'address' => 'Via dei Melograni, 50142 Firenze',
            'latitude' => '43.77741',
            'longitude' => '11.22011',
            'beds' => 6,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'size' => 120,
            'description' => 'Affascinante casa di campagna con vista panoramica sulla campagna toscana',
            'price' => 100.00,
        ],
        [
            'name' => 'Attico di lusso',
            'address' => 'Viale della Vittoria, 00122 Roma',
            'latitude' => '41.72929,',
            'longitude' => '12.28798',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 80,
            'description' => 'Esclusivo attico con terrazza panoramica nel cuore di Roma',
            'price' => 800.00,
        ],
        [
            'name' => 'Casa in collina',
            'address' => 'Viale dei Pini, 50142 Firenze',
            'latitude' => '43.77924',
            'longitude' => '11.21495',
            'beds' => 3,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => 90,
            'description' => 'Affascinante casa con vista sulla collina toscana',
            'price' => 300.00,
        ],
        [
            'name' => 'Appartamento al mare',
            'address' => 'Viale Trento, 47921 Rimini',
            'latitude' => '44.06591',
            'longitude' => '12.5792',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'size' => 70,
            'description' => 'Accogliente appartamento con vista sul mare adriatico',
            'price' => 90.00,
        ],
        [
            'name' => 'Villa in campagna',
            'address' => 'Via delle Rose, 50025 Montespertoli',
            'latitude' => '43.69627,',
            'longitude' => '11.01391',
            'beds' => 10,
            'bedrooms' => 5,
            'bathrooms' => 4,
            'size' => 300,
            'description' => 'Splendida villa con piscina privata e vista sulla campagna toscana',
            'price' => 70.00,
        ],
        [
            'name' => 'Monolocale nel centro storico',
            'address' => 'Via dei Benci, 50122 Firenze',
            'latitude' => '43.76767',
            'longitude' => '11.2594',
            'beds' => 2,
            'bedrooms' => 0,
            'bathrooms' => 1,
            'size' => 30,
            'description' => 'Accogliente monolocale nel cuore del centro storico',
            'price' => 90.00,
        ],
        [
            'name' => 'Villa degli Ulivi',
            'address' => 'Via degli Ulivi, 95123 Catania CT',
            'latitude' => '37.52557',
            'longitude' => '15.05628',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => 100,
            'description' => 'Splendida villa immersa nel verde degli ulivi, con vista mozzafiato sul mare della Sicilia. Perfetta per una vacanza rilassante e lontana dal caos della città.',
            'price' => 145.50,
        ],
        [
            'name' => 'Casa del Pescatore',
            'address' => 'Via del Mare, 97010 Modica RG',
            'latitude' => '36.7128',
            'longitude' => '14.77913',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Deliziosa casetta situata a pochi passi dal mare, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto e dotata di tutti i comfort.',
            'price' => 95.00,
        ],
    ],

    'users' => [
        [
            'name' => 'Carmelo',
            'lastname' => 'Palumbo',
            'username' => 'paluc',
            'email' => 'carmelopalumbo@boolbnb.com',
            'password' => '12345678',
            'date_of_birth' => '1997-04-26'
        ],
        [
            'name' => 'Carmelo',
            'lastname' => 'Miuccio',
            'username' => 'themrstraffy',
            'email' => 'carmelomiuccio@boolbnb.com',
            'password' => '12345678',
            'date_of_birth' => '1994-05-27'
        ],
        [
            'name' => 'Eugenio',
            'lastname' => 'Belardinelli',
            'username' => 'eugenio21',
            'email' => 'eugeniobelardinelli@boolbnb.com',
            'password' => '12345678',
            'date_of_birth' => '1992-04-21'
        ],
        [
            'name' => 'Michele',
            'lastname' => 'Zancolò',
            'username' => 'zanco',
            'email' => 'michelezancolo@boolbnb.com',
            'password' => '12345678',
            'date_of_birth' => '1997-05-19'
        ],
        [
            'name' => 'Jessica',
            'lastname' => 'Tartaglia',
            'username' => 'fr_jess',
            'email' => 'jessicatartaglia@boolbnb.com',
            'password' => '12345678',
            'date_of_birth' => '1985-05-26'
        ],
        [
            'name' => 'Appartamento Milano',
            'address' => 'P.za del Duomo, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.19226',
            'beds' => 4,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'size' => 80,
            'description' => 'Appartamento elegante in Piazza Duomo: Ampio appartamento con finiture di lusso, a pochi passi dalla Cattedrale di Milano.',
            'price' => 90.00,
        ],
        [
            'name' => 'Suite degli ospiti',
            'address' => 'P.za del Duomo, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.19005',
            'beds' => 1,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Appartamento moderno in Piazza Duomo: Appartamento di design con vista sulla Piazza Duomo, dotato di tutti i comfort.',
            'price' => 95.00,
        ],
        [
            'name' => 'Appartamento luminoso',
            'address' => 'P.za del Duomo, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.19205',
            'beds' => 3,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => 70,
            'description' => 'Appartamento accogliente in Piazza Duomo: Appartamento caldo e accogliente, arredato con gusto e posizionato in un palazzo storico.',
            'price' => 75.00,
        ],
        [
            'name' => 'Appartamento',
            'address' => 'P.za del Duomo, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.17225',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Monolocale accogliente in Piazza Duomo: Delizioso monolocale dallo stile contemporaneo, con vista sulla piazza più famosa di Milano.',
            'price' => 45.00,
        ],
        [
            'name' => 'Stanza Privata',
            'address' => 'P.za del Duomo, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.19285',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Deliziosa casetta situata a pochi passi dal Duomo.',
            'price' => 55.00,
        ],
        [
            'name' => 'Appartamento Duomo',
            'address' => 'P.za del Duomo, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.19625',
            'beds' => 7,
            'bedrooms' => 5,
            'bathrooms' => 3,
            'size' => 150,
            'description' => 'Attico di lusso in Piazza Duomo: Attico di design, con ampie vetrate panoramiche e una splendida terrazza privata con vista sulla Cattedrale di Milano.',
            'price' => 295.00,
        ],
        [
            'name' => 'Stanza in centro',
            'address' => 'P.za del Duomo, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.19225',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Monolocale accogliente in Piazza Duomo: Delizioso monolocale dallo stile contemporaneo, con vista sulla piazza più famosa di Milano.',
            'price' => 65.00,
        ],
        [
            'name' => 'Casa della musica',
            'address' => 'Piazza della Scala, 5, 20121 Milano MI',
            'latitude' => '45.46796',
            'longitude' => '9.18781',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Monolocale accogliente vicino al Teatrro alla Scala: Delizioso monolocale dallo stile contemporaneo, con vista sul teatro.',
            'price' => 85.00,
        ],
        [
            'name' => 'Appartamento in centro',
            'address' => 'Via Guglielmo Marconi, Piazza Armando Diaz, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.19225',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Loft esclusivo in Piazza Duomo: Luminoso loft di design con vista sulla Cattedrale di Milano, perfetto per chi cerca uno spazio unico e raffinato.',
            'price' => 135.00,
        ],
        [
            'name' => 'Appartamento vista Duomo',
            'address' => 'P.za del Duomo, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.18825',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Loft esclusivo in Piazza Duomo: Luminoso loft di design con vista sulla Cattedrale di Milano',
            'price' => 195.00,
        ],
        [
            'name' => 'Stanza in Duomo',
            'address' => 'P.za del Duomo, 16, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.18725',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Deliziosa casetta situata a pochi passi dal mare, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto e dotata di tutti i comfort.',
            'price' => 105.00,
        ],
        [
            'name' => 'Casa City Life',
            'address' => 'Via Ambrogio Spinola, 8, 20149 Milano MI',
            'latitude' => '45.47543',
            'longitude' => '9.15288',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'size' => 90,
            'description' => 'Deliziosa casetta ideale per una famiglia in cerca di relax e tranquillità.',
            'price' => 95.00,
        ],
        [
            'name' => 'Appartamento vista parco',
            'address' => 'Via Ambrogio Spinola, 20149 Milano MI',
            'latitude' => '45.47543',
            'longitude' => '9.15288',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Casa situata a pochi passi dal centro, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto e dotata di tutti i comfort.',
            'price' => 75.00,
        ],
        [
            'name' => 'Appartamento vista City Life',
            'address' => 'Via Ambrogio Spinola, 20149 Milano MI',
            'latitude' => '45.47543',
            'longitude' => '9.15288',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Delizioso appartamento situato a pochi passi dal centro di City Life, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto e dotata di tutti i comfort.',
            'price' => 95.00,
        ],
        [
            'name' => 'Stanza singola City Life',
            'address' => 'Via Ambrogio Spinola, 20149 Milano MI',
            'latitude' => '45.47543',
            'longitude' => '9.15288',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Deliziosa stanza a pochi passi dal centro di City Life, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto.',
            'price' => 85.00,
        ],
        [
            'name' => 'Appartamento San Siro',
            'address' => 'Via Ambrogio Spinola, 20149 Milano MI',
            'latitude' => '45.47543',
            'longitude' => '9.15288',
            'beds' => 5,
            'bedrooms' => 4,
            'bathrooms' => 4,
            'size' => 250,
            'description' => 'Delizioso appartamento situato a pochi passi dal centro di City Life, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto e dotata di tutti i comfort.',
            'price' => 595.00,
        ],
        [
            'name' => 'Appartamento in centro',
            'address' => 'Via Guglielmo Marconi, Piazza Armando Diaz, 20122 Milano MI',
            'latitude' => '45.46361',
            'longitude' => '9.19225',
            'beds' => 4,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'size' => 80,
            'description' => 'Delizioso appartamento situato a pochi passi dal Duomo, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto e dotata di tutti i comfort.',
            'price' => 235.00,
        ],
        [
            'name' => 'Casa in City Life Milano',
            'address' => 'Via Ambrogio Spinola, 20149 Milano MI',
            'latitude' => '45.47543',
            'longitude' => '9.15288',
            'beds' => 5,
            'bedrooms' => 3,
            'bathrooms' => 4,
            'size' => 250,
            'description' => 'Deliziosa casetta situata a pochi passi dalla City Life',
            'price' => 295.00,
        ],
        [
            'name' => 'Residenze Libeskind',
            'address' => 'Via Ambrogio Spinola, 20149 Milano MI',
            'latitude' => '45.47540',
            'longitude' => '9.15280',
            'beds' => 7,
            'bedrooms' => 6,
            'bathrooms' => 3,
            'size' => 250,
            'description' => 'Deliziosa casetta nel quartiere di Milano Libeskind',
            'price' => 495.00,
        ],
        [
            'name' => 'Stanza in una Residenza Libeskind',
            'address' => 'Via Ambrogio Spinola, 20149 Milano MI',
            'latitude' => '45.47543',
            'longitude' => '9.15288',
            'beds' => 1,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 30,
            'description' => 'Stanza confortevole in una delle meravigliose case Libeskind',
            'price' => 95.00,
        ],
        [
            'name' => 'Appartamento del Pescatore',
            'address' => 'Fondamenta Fianco Ponte Lungo, 30133 Venezia VE',
            'latitude' => '45.426',
            'longitude' => '12.32897',
            'beds' => 3,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Appartamento accogliente sul canale della Giudecca',
            'price' => 55.00,
        ],
        [
            'name' => 'La Casa dei Canali',
            'address' => 'Fondamenta Fianco Ponte Lungo, 30133 Venezia VE',
            'latitude' => '45.426',
            'longitude' => '12.32897',
            'beds' => 5,
            'bedrooms' => 4,
            'bathrooms' => 3,
            'size' => 150,
            'description' => 'Casa sul canale dell\'isola Giudecca con vista su tutta Venezia',
            'price' => 135.00,
        ],
        [
            'name' => 'La Suite del Doge',
            'address' => 'Calle Città di Fano, 30133 Venezia VE',
            'latitude' => '45.4251',
            'longitude' => '12.33711',
            'beds' => 3,
            'bedrooms' => 1,
            'bathrooms' => 3,
            'size' => 150,
            'description' => 'Splendida Suite a Venezia, lusso e confort a non finire per passare un weekend di coppia romantico nelle città del Doge',
            'price' => 295.00,
        ],
        [
            'name' => 'Stanza a Campo Santa Margherita',
            'address' => 'Sestiere Dorsoduro, 30123 Venezia VE',
            'latitude' => '45.4338',
            'longitude' => '12.32834',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Confrotevole stanza situata nel centro di Venezia, ideale per una coppia in cerca di relax e tranquillità. Arredata con gusto.',
            'price' => 95.00,
        ],
        [
            'name' => 'Casa del Pescatore',
            'address' => 'Sestiere Dorsoduro, 30123 Venezia VE',
            'latitude' => '45.4338',
            'longitude' => '12.32436',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'size' => 80,
            'description' => 'Deliziosa casetta situata a pochi passi dal Grand Canal, ideale per una famiglia in visita a Venezia. Arredata con gusto e dotata di tutti i comfort.',
            'price' => 195.00,
        ],
        [
            'name' => 'Casa del Pescatore',
            'address' => 'Fondamenta Zattere Al Ponte Lungo, 30123 Venezia VE',
            'latitude' => '45.43043',
            'longitude' => '12.32249',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => 100,
            'description' => 'Appartamento sul Rio dei Carmini, vicino alla stazione San Basilio per spostarsi con il Traghetto.',
            'price' => 105.00,
        ],
        [
            'name' => 'Casa nel cuore di Venezia',
            'address' => 'C. de Mezzo, 30125 Venezia VE',
            'latitude' => '45.43588',
            'longitude' => '12.33547',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'size' => 110,
            'description' => 'Casa accogliente nel cuore di Venezia. Situata a pochi passi dalla stazione per avere degli spostamenti comdi da e per la città.',
            'price' => 195.00,
        ],
        [
            'name' => 'Appartamento del Pescatore',
            'address' => 'Fondamenta Zattere Al Ponte Lungo, 30123 Venezia VE',
            'latitude' => '45.43053',
            'longitude' => '12.32249',
            'beds' => 3,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => 90,
            'description' => 'Appartamento sul Rio dei Carmini, a pochi passi dalla zona Universitaria e vicino alla stazione San Basilio per spostarsi con il Traghetto.',
            'price' => 95.00,
        ],
        [
            'name' => 'Stanza a Venezia',
            'address' => 'C. de le Altane, 30100 Venezia VE',
            'latitude' => '45.44377',
            'longitude' => '12.32241',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Stanza a venezia, semplice e accogliente per passare un ottima vacanza ',
            'price' => 55.00,
        ],
        [
            'name' => 'Appartamento vista Piazza San Marco',
            'address' => 'S. Marco, 30124 Venezia VE',
            'latitude' => '45.4345',
            'longitude' => '12.33788',
            'beds' => 5,
            'bedrooms' => 4,
            'bathrooms' => 4,
            'size' => 150,
            'description' => 'Delizioso apartamento con vista San Marco, lusso e confort di ogni genere',
            'price' => 595.00,
        ],
        [
            'name' => 'Villetta a Capri',
            'address' => 'Via Krupp, 80076 Capri NA',
            'latitude' => '40.5462',
            'longitude' => '14.23976',
            'beds' => 7,
            'bedrooms' => 5,
            'bathrooms' => 4,
            'size' => 290,
            'description' => 'Villetta a Capri con vista sui faraglioni .',
            'price' => 395.00,
        ],
        [
            'name' => 'Casa vista Capri',
            'address' => 'Via Krupp, 80076 Capri NA',
            'latitude' => '40.5422',
            'longitude' => '14.23978',
            'beds' => 5,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => 150,
            'description' => 'Casa con vista mare, semplice e accogliente per passare un ottima vacanza in tranquillità.',
            'price' => 295.00,
        ],
        [
            'name' => 'Appartamento vista Mare',
            'address' => 'Via Crotta delle Felci, 80076 Capri NA',
            'latitude' => '40.54705',
            'longitude' => '14.23336',
            'beds' => 5,
            'bedrooms' => 4,
            'bathrooms' => 4,
            'size' => 150,
            'description' => 'Appartamento a pochi passi dalle famose spiagge di Capri con tutti i confort necesari.',
            'price' => 225.00,
        ],
        [
            'name' => 'Stanza a Capri',
            'address' => 'Via Crotta delle Felci, 80076 Capri NA',
            'latitude' => '40.54735',
            'longitude' => '14.23336',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 90,
            'description' => 'Stanza accogliente, arredamento moderno e vista mozzafiato.',
            'price' => 85.00,
        ],
        [
            'name' => 'Appartamento vista Colosseo',
            'address' => 'Viale della Domus Aurea 1, 00184 Roma',
            'latitude' => '41.89075',
            'longitude' => '12.49805',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => 90,
            'description' => 'Appartamento moderno con vista sul colosseo',
            'price' => 500.00,
        ],
        [
            'name' => 'Appartamento a due passi dal Colosseo',
            'address' => 'Via Celimontana, 34, 00184 Roma RM',
            'latitude' => '41.88794',
            'longitude' => '12.49638',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 50,
            'description' => 'Piccolo Appartamento a due passi dal colosseo',
            'price' => 200.00,
        ],
        [
            'name' => 'Appartamento zona stazione termini',
            'address' => 'Via Giovanni Amendola, 57, 00185 Roma RM',
            'latitude' => '41.89994',
            'longitude' => '12.49969',
            'beds' => 4,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'size' => 110,
            'description' => 'Appartamento spazioso dotato di tutti i confort, vicino alla stazione',
            'price' => 400.00,
        ],
        [
            'name' => 'Appartamento Tufello',
            'address' => 'Via delle Vigne Nuove, 45, 00139 Roma RM',
            'latitude' => '41.94708',
            'longitude' => '12.53715',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 70,
            'description' => 'Piccolo Appartamento idele per le coppie in zona Tufello',
            'price' => 150.00,
        ],
        [
            'name' => 'Suite di lusso vicino al Pantheon',
            'address' => 'P.za di Pietra, 26, 00186 Roma RM',
            'latitude' => '41.89997',
            'longitude' => '12.47892',
            'beds' => 1,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 80,
            'description' => 'Suite Moderna dotata di tutti i confort, con vista sul Pantheon',
            'price' => 500.00,
        ],
        [
            'name' => 'Stanza Pigneto',
            'address' => 'Via Prenestina, 42, 00176 Roma RM',
            'latitude' => '41.8912',
            'longitude' => '12.51976',
            'beds' => 1,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 20,
            'description' => 'stanza luminosa zona pigneto ideale per universitari',
            'price' => 40.00,
        ],
        [
            'name' => 'B&B a 2 passi da Roma',
            'address' => 'Viale Odone Belluzzi, 223, 00128 Roma RM',
            'latitude' => '41.77962',
            'longitude' => '12.42846',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 35,
            'description' => 'B&B vicino alla Riserva Naturale Statale Tenuta di Castelporziano, un luogo magnifico immerso nella natura.',
            'price' => 150.00,
        ],
        [
            'name' => 'Appartamento EUR',
            'address' => 'Viale Europa, 170, 00144 Roma RM',
            'latitude' => '41.83139',
            'longitude' => '12.46663',
            'beds' => 5,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'size' => 120,
            'description' => 'Appartamento Spazioso ideale per aziende in piena zona EUR',
            'price' => 400.00,
        ],
        [
            'name' => 'Stanza San Basilio',
            'address' => 'Via Cingoli, 15, 00156 Roma RM',
            'latitude' => '41.94131',
            'longitude' => '12.58505',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 20,
            'description' => 'Stanza zona san basilio con bagno indipendente',
            'price' => 60.00,
        ],
        [
            'name' => 'Suite Trevi',
            'address' => 'Vicolo Scanderbeg, 00187 Roma RM',
            'latitude' => '41.90058',
            'longitude' => '12.48494',
            'beds' => 1,
            'bedrooms' => 1,
            'bathrooms' => 2,
            'size' => 100,
            'description' => 'Suite lussusissima nel centro storico romano a due passi dalla Fontana di Trevi, vista fontana di Trevi',
            'price' => 600.00,
        ],
        [
            'name' => 'Appartamento Prati',
            'address' => 'Via Cola di Rienzo, 00192 Roma RM',
            'latitude' => '41.90911',
            'longitude' => '12.46989',
            'beds' => 4,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'size' => 100,
            'description' => 'Appartamento moderno in una zona esclusiva di Roma',
            'price' => 200.00,
        ],
        [
            'name' => 'B&B BioParco',
            'address' => 'Via Ulisse Aldrovandi, 15, 00197 Roma RM',
            'latitude' => '41.91864',
            'longitude' => '12.48493',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 40,
            'description' => 'B&B vicino al BioParco di Roma con bagno indipendente',
            'price' => 60.00,
        ],
        [
            'name' => 'Appartamento la Breccia',
            'address' => 'Corso d\'Italia, 108, 00187 Roma RM',
            'latitude' => '41.91004',
            'longitude' => '12.50084',
            'beds' => 3,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'size' => 80,
            'description' => 'Appartamento Storico dotato di tutti i confort',
            'price' => 120.00,
        ],
        [
            'name' => 'Guidonia\'s House',
            'address' => 'Via Lago Dei Tartari, 00012 Guidonia RM',
            'latitude' => '41.9581',
            'longitude' => '12.70342',
            'beds' => 6,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'size' => 150,
            'description' => 'Casa molto luminosa vicino zona industriale di guidonia ',
            'price' => 200.00,
        ],
        [
            'name' => 'La casa di Nerone',
            'address' => 'Via Bagnoregio, 00189 Roma RM',
            'latitude' => '41.97142',
            'longitude' => '12.43998',
            'beds' => 6,
            'bedrooms' => 4,
            'bathrooms' => 3,
            'size' => 160,
            'description' => 'Appartamento molto spazioso dotato di cucina abitabile e 2 stanze matrimoniali',
            'price' => 400.00,
        ],
        [
            'name' => 'Stanza Aeroporto',
            'address' => 'Viale J. F. Kennedy, 161, 00043 Ciampino RM',
            'latitude' => '41.81155',
            'longitude' => '12.59379',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 35,
            'description' => 'Una stanza pensata per chi deve passare una notte prima di un viaggio',
            'price' => 40.00,
        ],
        [
            'name' => 'Appartamento Forza Roma',
            'address' => 'Via Gustavo D\'Arpe, 00128 Roma RM',
            'latitude' => '41.76476',
            'longitude' => '12.47745',
            'beds' => 5,
            'bedrooms' => 4,
            'bathrooms' => 2,
            'size' => 150,
            'description' => 'Appartamento vicino al campo di allenamento della AS Roma',
            'price' => 300.00,
        ],
        [
            'name' => 'Stanza Biomedica',
            'address' => 'Via Danilo Gavagnin, 30, 00128 Selcetta RM',
            'latitude' => '41.76832',
            'longitude' => '12.47128',
            'beds' => 1,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 20,
            'description' => 'Stanza vicino campus biomedico, ideale per universitari',
            'price' => 50.00,
        ],
        [
            'name' => 'Stanza stop & go',
            'address' => 'Via Portuense, 2460, 00054 Fiumicino RM',
            'latitude' => '41.78528',
            'longitude' => '12.27619',
            'beds' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'size' => 30,
            'description' => 'Stanza a pochi passi dall\'aeroporto di Fiumicino, ideale per chi deve fermarsi una notte prima di partire',
            'price' => 90.00,
        ],
        [
            'name' => 'Appartamento Cesaroni',
            'address' => 'Largo Angelo Fochetti, 357-307, 00154 Roma RM',
            'latitude' => '41.86708',
            'longitude' => '12.49568',
            'beds' => 5,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'size' => 120,
            'description' => 'Appartamento moderno zona Garbatella, dotato di tutti i comfort',
            'price' => 500.00,
        ],
    ],

    'services' => ['cucina', 'wi-fi', 'posto auto', 'tv', 'piscina', 'aria condizionata', 'vista mare', 'ascensore', 'animali ammessi', 'giardino'],

    'sponsors' => [
        [
            'name' => 'bronze',
            'price' => 2.99,
            'duration' => 2
        ],
        [
            'name' => 'silver',
            'price' => 5.99,
            'duration' => 5
        ],
        [
            'name' => 'gold',
            'price' => 9.99,
            'duration' => 10
        ],
    ],

    'users' => [
        [
            'name' => 'Carmelo',
            'lastname' => 'Palumbo',
            'username' => 'paluc',
            'email' => 'carmelopalumbo@boolbnb.com',
            'password' => '12345678',
            'date_of_birth' => '1997-04-26'
        ],
        [
            'name' => 'Carmelo',
            'lastname' => 'Miuccio',
            'username' => 'themrstraffy',
            'email' => 'carmelomiuccio@boolbnb.com',
            'password' => '12345678',
            'date_of_birth' => '1994-05-27'
        ],
        [
            'name' => 'Eugenio',
            'lastname' => 'Belardinelli',
            'username' => 'eugenio21',
            'email' => 'eugeniobelardinelli@boolbnb.com',
            'password' => '12345678',
            'date_of_birth' => '1992-04-21'
        ],
        [
            'name' => 'Michele',
            'lastname' => 'Zancolò',
            'username' => 'zanco',
            'email' => 'michelezancolo@boolbnb.com',
            'password' => '12345678',
            'date_of_birth' => '1997-05-19'
        ],
        [
            'name' => 'Jessica',
            'lastname' => 'Tartaglia',
            'username' => 'fr_jess',
            'email' => 'jessicatartaglia@boolbnb.com',
            'password' => '12345678',
            'date_of_birth' => '1985-05-26'
        ]
    ],


];
